### ISSUE TITLE
marketing - bounty emails should shill grants and kudos

### ISSUE THREAD

**Issue by owocki** [gitcoinco/gitcoin-erc721#110]
This is the current bounty submission email:

![screencapture-gitcoin-co-_administration-email-new_work_submission-2018-09-24-10_01_29](https://user-images.githubusercontent.com/513929/45963646-d2804000-bfe0-11e8-9a29-4bd579c3e67f.png)

This is the current funds paid email:

![screencapture-gitcoin-co-_administration-email-new_bounty_acceptance-2018-09-24-10_00_52](https://user-images.githubusercontent.com/513929/45963604-bda3ac80-bfe0-11e8-9cae-8f4237c09dd1.png)

it'd be opportune to shill kudos in these emails... to let users know they can show appreciation for each other by sending kudos!

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2629
