### ISSUE TITLE
Add ability for users to transfer already existing Kudos clones

### ISSUE THREAD

**Issue by jasonrhaas** [gitcoinco/gitcoin-erc721#128]
New use case:  We may want to give existing Gitcoin users already pre-minted Kudos clones that they can give out to the people working on their projects.

So this is a different flow than the regular "Send Kudos from Marketplace", since we (Gitcoin) are paying for the cost of the Kudos clone.

One possible scenario:
- Gitcoin "pre clones" a bunch of Kudos, and the Repo maintainer receives an email telling them that they have "Kudos available to send"
- The Kudos sit in a "voucher" type state, possibly in the marketplace, waiting for the Repo Maintainer to send the Kudos to someone.
- Once they have decided that they want to use the Kudos to send to someone, at that point it gets cloned and send to the final destination.

Technical notes:
- Transfer of kudos objects is straightforward in the Solidity Contract
- This is a new UX flow for the Gitcoin App
- Will have to do something similar to the "Indirect" send method, since we don't want the Repo Maintainer to have to pay for gas or the cost of the Kudos.  It will need to be a rawTransaction.
- Maybe we just have a Gitcoin Kudos "slush fund" that is filled with some Ether, that gets used to pay for these Kudos?  Ultimately if we own the Gen0 Kudos the money comes back to us anyway.

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2624
