### ISSUE TITLE
if a kudos is transfered away, it sould grey out on the profile (instead of being removed)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/gitcoin-erc721#131]
ref: https://gitcoincore.slack.com/archives/CAXCZR8K0/p1538437626000100

if a kudos is transfered away, it sould grey out on the profile (instead of being removed)

the data trail that they received the kudos at all is what matters for reputation.

this also allows resale-ability of kudos

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2623
