### ISSUE TITLE
Add Artist Bio on Kudos Homepage

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/gitcoin-erc721#178]
## Add Artist Bio on Kudos Homepage

- [ ] Update Artist Bio with the following Information:

Octavian Todiruț
ConsenSys Product Designer @ Cellarius

I am a long time graphic designer, art director and product designer. A fancy way of saying "I am moving the mouse or pencil around, playing with shapes and colors." I like getting lost in everything art, photography, design and architecture and their history. When I don't do any of the above, I walk, travel or sometimes play a game.

- [ ] Include bio image inside of a Kudos shape

![me](https://user-images.githubusercontent.com/238235/46821782-b22de080-cd57-11e8-8d07-b40aaa5807c2.jpg)

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2609
