### ISSUE TITLE
Add ability to send a Kudos using only Eth address

### ISSUE THREAD

**Issue by jasonrhaas** [gitcoinco/gitcoin-erc721#181]
> It seems that there is a use case for sending cloned kudos to people that are not on the gitcoin platform. Currently the Kudos Send requires a Gitcoin or Github username.  But we have a case here where I need to send Kudos to someone and only have the address:

https://github.com/mbeacom/gitcoin-erc721/issues/172#issuecomment-429448305

We would like to have a UI that allows this rather than relying on a management command.

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2606
