### ISSUE TITLE
Add Kudos generation to badge

### ISSUE THREAD

**Issue by jasonrhaas** [gitcoinco/gitcoin-erc721#198]
Now that we have the ability to support Kudos on multiple contracts, we should make it clear to the user which contract the Kudos is on.  Old Kudos will be tradable and transferable but not mintable or clonable.

Somewhere, maybe in the database, there will be a mapping like this:

Gen 1 = contract_address_1
Gen 2 = contract_address_2
Gen 3 = contract_address_current

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2602
