### ISSUE TITLE
Add contract address and network to Kudos details page

### ISSUE THREAD

**Issue by jasonrhaas** [gitcoinco/gitcoin-erc721#201]
Related to https://github.com/mbeacom/gitcoin-erc721/issues/200

We need to be able to clearly identify from the UI which contract and network the Kudos belongs to.  Otherwise it will get very confusing once we have multiple contracts and generations of kudos deployed.

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2599
