### ISSUE TITLE
as a user, i want to be able to send 100 kudos at a time, because marketing.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/gitcoin-erc721#209]
as a user, i want to be able to send 100 kudos at a time, because marketing.

example: send a devcon kudos at the end of my devcon preso

what:
- a page, based upon the current receive page, called bulk_receive that accepts a receive web3 address,
and transfers the specified kudos to it
- since we cannot do this securely in the current architecture of receive (because of the private key being exposed on the frontend, and if we put too much ETH in the private key / account, then ppl will steal it), we must built a new architecture.
- i suggest this new architecture be based in web3py.  the kudos will be sent if/when someone submits a POST request on the form 

other specifications:
- user must be logged in to receive a kudos.
- form submission will fail if there aren't enough clones available
- form submission will fail (silently) if you try to get more than one kudos (sybyll vectors we should close: ip address AND web3 address)

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2598
