### ISSUE TITLE
As a user, I want to list my artifact in the marketplace so I can make $$$ from it.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/gitcoin-erc721#22]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want to list my artifact in the marketplace so I can make $$$ from it.

### How it Works

As a user, I want to list my artifact in the marketplace so I can make $$$ from it.

In this view of the world, which is an augmentation of #21, each `TokenCreationRequests` has a `list_in_marketplace` (bool) and `num_clones` (int) attribute.  

If `list_in_marketplace` is True, then `num_clones` artifacts will be listed in the erc 721 marketplace.

`num_clones` will affect the rareness score of an artifact.

When a user purchases an artifact from the marketplace, 80% of the revenue will go to the user who created it.  20% will go to Gitcoin Core.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2652
