### ISSUE TITLE
As a user, I want to 'equip' my artifact on my avatar, so I can show it off in my avatar.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/gitcoin-erc721#23]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want to 'equip' my artifact on my avatar, so I can show it off in my avatar.

### How it Works

In this view of the world, artifacts have two visual assets associated with them.

* badge -- shown on their profile
* equipped_asset -- shown on their avatar and in their avatar builder.

We would have to augment the artifact creation flow, and the artifact listings to update for these two visual assets.

We would also have to update the avatar builder to allow users to equip these assets.

### Example Use Case

For example, if I got a badge called "ruby knight", it could come with a knight suit that I could them equip on my gitcoin avatar.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2651
