### ISSUE TITLE
v2 - Reputation/Game Mechanics

### ISSUE THREAD

**Issue by owocki** [gitcoinco/gitcoin-erc721#25]
(not ready to be worked on yet)

Do the artifacts bestow any ‘powers’ on the users?
How do 721 tokens fall into Gitcoin's reputation system?
Making it a playable game eventually could be very cool, but the shape of this would have to evolve.  
How do we want to provide [variable rewards to contributors](https://github.com/gitcoinco/web/issues/230#issuecomment-360932251)?
What is the game mechanic model to build into this?

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2650
