### ISSUE TITLE
STRATEGY POV on the Role of 721 + Gitcoin Reputation

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/gitcoin-erc721#29]
As core team members, we would like to have shared understanding on v1 of core principles on how the erc-721 works with reputation.

Questions to answer:

1) What is the role of 721?
Unique Identity art asset - transportable, market Gitcoin, revenue for Gitcoin

2) What is the role of reputation?
- Track good/bad folks work habits
- Does good reputation allow you access to higher value work/ cooler projects?
- Encourage developers to be great
- Allow funders/developers to have a sense of whom they're working with, reliability, etc
- Is Gitcoin reputation only system generated or peer to peer as well (we discussed peer to peer)?
- Allow community members to award each other?

3) What are the principles of our reputation system (or a working hypothesis)?

4) Example of an important principles (imho)
- Reputation is not an asset that you can buy.
- The credential that you get issued by doing x should this or should it not be a tradable asset (but maybe you and only you have the ability to recreate that asset and put a spin on it like color and share/sell?).

5) How do we think about approving art to be made/remade? Do we want to control it that granularly?Is there a voting aspect?

6) How do we make this exciting so that people want to do have a Gitcoin avatar/ be part of our platform? Hidden golden hats that people can try and acquire, etc?

These are some things I've been thinking about based on convos around 721 and reputation at the retreat.
Maybe we move this to a word doc.

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2648
