### ISSUE TITLE
STRATEGY Working Theory of V1 Reputation System

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/gitcoin-erc721#33]
As a core team, we should have a shared understanding of the initial attributes that make up the V1 of our reputation system.

Examples:

- number of days it takes to complete a task
- responsiveness to comment/feedback
- number of projects completed on gitcoin Platform
- number of tips received/sent

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2647
