### ISSUE TITLE
DEV FRONT END Approach to ERC-721 Project

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/gitcoin-erc721#34]
As a user, I would like to see a consistent front-end experience to this project.
As a core team member - I would like to be able to easily build using predefined styles for this project.

Define front end approach so that this could be an example of how the core Gitcoin product adopts in terms of implementation.

Definition of Done
Predefined layouts, css styles for buttons, divs, modules

@SaptakS @thelostone-mc please define

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2646
