### ISSUE TITLE
As an admin, I want to to staff the 'mint new tokens' flow with talented illustrators, so we can mint new tokens.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/gitcoin-erc721#38]
As an admin, I want to to staff the 'mint new tokens' flow with talented illustrators, so we can mint new tokens.

We will need an illustrator within our price point(s) that can work fastly to turn around new illustrations for our community.  

They need to be 

* respoinsive
* good 
* within our price range

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2644
