### ISSUE TITLE
partnerships/sponsored badges

### ISSUE THREAD

**Issue by owocki** [gitcoinco/gitcoin-erc721#40]
from @PixelantDesign 

> I think partnerships/sponsored badges could elevate the platform. Like if we created a set of badges and just gave them to people who we know are big to do’s in the ethereum development or oss industry. Like if someone gets a badge from VItalik, Joe Lubin, Piper - that’s a big deal.

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2643
