### ISSUE TITLE
Show Gitcoin "loading" gif when token is still being sync'ed to the blockchain

### ISSUE THREAD

**Issue by jasonrhaas** [gitcoinco/gitcoin-erc721#48]
Right now there is no feedback to users if we are waiting on the blockchain.

Should be able to re-use code from the Gitcoin App for this.

UPDATE:
Right now this will just be a confirmation page on any new Kudos clone, telling the user that the Kudos will be available on the Blockchain and Gitcoin Profile after a few minutes.

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2642
