### ISSUE TITLE
Integrate Kudos Into Bounties - V1

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/gitcoin-erc721#81]
**Integration Points**
- Profile drop down below Send Tips --"Send Kudos"
- Single Payout Screen below tips

**Proposal**
- Implement typedown to find Kudos as seen in the flow below.
- Implement alert to notify users that there will be 3 separate transactions if tip and kudos are also included in bounty payout.

![integrate kudos](https://user-images.githubusercontent.com/238235/45360066-6ba06700-b59c-11e8-997f-a446c207dbb1.png)

**Alternate Ideas**
A simple link to the Kudos market place is the lowest lift option but not a seamless and a less ideal user experience.

@jasonrhaas @owocki @octavioamu 

[Kudos Integration Final.zip](https://github.com/mbeacom/gitcoin-erc721/files/2443432/Kudos.Integration.Final.zip)

![kudos integration_final](https://user-images.githubusercontent.com/238235/46433073-eb45cf80-c71d-11e8-8cdd-ec2b8c16f05c.jpg)

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2635
