### ISSUE TITLE
Manage Kudos from an Admin page

### ISSUE THREAD

**Issue by jasonrhaas** [gitcoinco/gitcoin-erc721#96]
Currently all of the Gen0 Kudos are minted via a Django Management command on the backend.  It reads from a YAML file and automatically mints all the Kudos.

However, we probably want the ability (as an Admin) to mint our own Kudos from the Front end as well.  This would involve filling out all the appropriate information on the form, and uploading an SVG image to use for the Kudos.

It would be like http://localhost:8000/kudos/mint, but for Admins only.

Related to #44

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2632
